CarSales.Web.UI/Controllers/HomeController.cs
/// <summary>
/// ================================================
/// 
/// CarSales - The VehicleManagement System
/// Copyright (c) 2021
/// Author: Priya Gupta
/// File: HomeController.cs 
/// Description: Home Controller Class
/// 
/// ================================================
/// </summary>
namespace CarSales.Web.UI.Controllers
{
    using System.Web.Mvc;

    /// <summary>
    /// Class HomeController.
    /// </summary>
    /// <seealso cref="System.Web.Mvc.Controller" />
    public class HomeController : Controller
    {
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Abouts this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        /// <summary>
        /// Contacts this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CarSales.Web.UI/Controllers/VehicleController.cs
/// <summary>
/// ================================================
/// 
/// CarSales - The VehicleManagement System
/// Copyright (c) 2021
/// Author: Priya Gupta
/// File: VehicleController.cs 
/// Description: Vehicle Controller Class
/// 
/// ================================================

namespace CarSales.Web.UI.Controllers
{
    using System.Web.Mvc;
    using CarSales.VehicleManagement;


    /// <summary>
    /// Class VehicleController.
    /// </summary>
    /// <seealso cref="System.Web.Mvc.Controller" />
    public class VehicleController : Controller
    {
        IVehicle _IVehicle;

        /// <summary>
        /// Initializes a new instance of the <see cref="VehicleController"/> class.
        /// </summary>
        public VehicleController()
        {
            ViewBag.VehicleType = Constants.VEHICLE_TYPE;
            ViewBag.BodyType = Constants.BODY_TYPE;
            _IVehicle = new Vehicle();
            
        }

        /// <summary>
        /// Details this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Details()
        {
         return View(Concrete.DBVehicle.SelectCarList());

        }


        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult Create()
        {
         
            return View();
         
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Car carModels)
        {
            try
            {
                Concrete.DBVehicle.InsertCarList(carModels);
                return RedirectToAction("Details");
            }
            catch
            {
                return View();
            }
        }
       
    }
}

CarSales.Web.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>


<p>Our Company XYZ Ltd (ASX: CAR) is the largest online automotive, motorcycle and marine classifieds business in Australia. Attracting more Indians interested in buying or selling cars, motorcycles, trucks, caravans and boats than any other classified group of websites.</p>

CarSales.Web.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    India, 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CarSales.Web.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<header class="intro">
    <div class="intro-body">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h1 class="brand-heading">CarSales MVP v1.0</h1>
                    <p class="intro-text"> 
                        Welcome to CarSales. <br />
                         Start by clicking 'Vehicle Management System' menu

                    </p>
                </div>
            </div>
        </div>
    </div>
</header>



<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

CarSales.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Car</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="~/home/#page-top">
                    &emsp; &emsp; &emsp; &emsp; &emsp;
                    <i class="glyphicon glyphicon-tree-conifer"></i>  <span class="light"> Car sales</span> group
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Vehicle Management System", "Details", "Vehicle")</li>
                        </ul>
                    </div>
            </div>
    </nav>
    @RenderBody()
    <hr />
    <footer>
        <div style="text-align:center;font-size:smaller">&copy;CarSales Inc. 2021 </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CarSales.Web.UI/Views/Vehicle/Create.cshtml
@model CarSales.VehicleManagement.Car

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
   
      
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
        
          
            @Html.LabelFor(model => model.SelectedVehicleType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.SelectedVehicleType, ViewBag.VehicleType as IEnumerable<SelectListItem>,new { @class = "form-control" })
                @*@Html.EditorFor(model => model.SelectedVehicleType, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.SelectedVehicleType, "", new { @class = "text-danger" })
             
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleMake,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleMake, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleMake, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VehicleEngine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VehicleEngine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VehicleEngine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoOfDoors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoOfDoors, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfDoors, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.NoOfWheels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoOfWheels, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfWheels, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedBodyType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.SelectedBodyType, ViewBag.BodyType as IEnumerable<SelectListItem>, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SelectedBodyType, "", new { @class = "text-danger" })
            </div>
        </div>

     
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarSales.Web.UI/Views/Vehicle/Details.cshtml
@model IEnumerable<CarSales.VehicleManagement.Car>

@{
    ViewBag.Title = "Index";
}

<h2></h2>


@using (Html.BeginForm("Create", "Vehicle", FormMethod.Get))
{

    @Html.DropDownList("type", ViewBag.VehicleType as IEnumerable<SelectListItem>, new { @class = "" })
 
            <input type="submit" value="Create" class="btn btn-default" />
   

}


<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SelectedVehicleType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VehicleYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VehicleMake)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VehicleModel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VehicleEngine)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoOfDoors)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoOfWheels)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SelectedBodyType)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SelectedVehicleType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleMake)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleModel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleEngine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoOfDoors)
            <td>
                @Html.DisplayFor(modelItem => item.NoOfWheels)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SelectedBodyType)
            </td>
        
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { id = item.VehicleId }) |
                @Html.ActionLink("Details", "Details", new { id = item.VehicleId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.VehicleId })
            </td>*@
        </tr>
    }

</table>